### ISSUE TITLE
Cannot import JSON file from Insomnia

### ISSUE THREAD

**Issue by lmantesbtm** [tiagohm/restler#52]
JSON file import not working. No error messages return. 

The file came from Insomnia, exported as JSON then tried importing to the collection section of the app.

Can't provide other details as there are no error messages that appears after selecting the JSON file to open.

**Comment by tiagohm** [comment]
Fixed it. Thanks for reporting the issue.

**Comment by JasonXDDD** [comment]
This problem still exists on my Android phone. No any response and just shutdown app.

This is environment
device: Pixel3 / Android Q
version: v1.0.0-beta9
Insomnia: v6.6.2 / export file: Insomnia v4 (JSON)
